In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm

# Billboard Year-End Hot 100 Charts 2000-2018

In [2]:
billboard100_df = pd.DataFrame(columns=['Title', 'Artist', 'Year'])
billboard100_df

Empty DataFrame
Columns: [Title, Artist, Year]
Index: []

In [3]:
url_template = 'https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_'

years = [2000, 2001, 2002, 2003, 2004, 2005, 2006, 
         2007, 2008, 2009, 2010, 2011, 2012, 2013,
         2014, 2015, 2016, 2017, 2018]

In [4]:
# 2000
url = url_template + str(2000)

temp_df = pd.read_html(url, header=0)[0]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2000

billboard100_df = billboard100_df.append(temp_df)

In [5]:
# 2001
url = url_template + str(2001)

temp_df = pd.read_html(url, header=0)[0]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2001

billboard100_df = billboard100_df.append(temp_df)

In [6]:
# 2002
url = url_template + str(2002)

temp_df = pd.read_html(url, header=0)[0]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2002

billboard100_df = billboard100_df.append(temp_df)

In [7]:
# 2003
url = url_template + str(2003)

temp_df = pd.read_html(url, header=0)[0]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2003

billboard100_df = billboard100_df.append(temp_df)

In [8]:
# 2004
url = url_template + str(2004)

temp_df = pd.read_html(url, header=0)[0]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2004

billboard100_df = billboard100_df.append(temp_df)

In [9]:
# 2005
url = url_template + str(2005)

temp_df = pd.read_html(url, header=0)[0]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2005

billboard100_df = billboard100_df.append(temp_df)

In [10]:
# 2006
url = url_template + str(2006)

temp_df = pd.read_html(url, header=0)[0]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2006

billboard100_df = billboard100_df.append(temp_df)

In [11]:
# 2007
url = url_template + str(2007)

temp_df = pd.read_html(url, header=0)[0]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2007

billboard100_df = billboard100_df.append(temp_df)

In [12]:
# 2008
url = url_template + str(2008)

temp_df = pd.read_html(url, header=0)[0]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2008

billboard100_df = billboard100_df.append(temp_df)

In [13]:
# 2009
url = url_template + str(2009)

temp_df = pd.read_html(url, header=0)[0]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2009

billboard100_df = billboard100_df.append(temp_df)

In [14]:
# 2010
url = url_template + str(2010)

temp_df = pd.read_html(url, header=0)[0]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2010

billboard100_df = billboard100_df.append(temp_df)

In [15]:
# 2011
url = url_template + str(2011)

temp_df = pd.read_html(url, header=0)[0]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2011

billboard100_df = billboard100_df.append(temp_df)

In [16]:
# 2012
url = url_template + str(2012)

temp_df = pd.read_html(url, header=0)[1]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2012

billboard100_df = billboard100_df.append(temp_df)

In [17]:
# 2013
url = url_template + str(2013)

temp_df = pd.read_html(url, header=0)[1]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2013

billboard100_df = billboard100_df.append(temp_df)

In [18]:
# 2014
url = url_template + str(2014)

temp_df = pd.read_html(url, header=0)[0]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2014

billboard100_df = billboard100_df.append(temp_df)

In [19]:
# 2015
url = url_template + str(2015)

temp_df = pd.read_html(url, header=0)[0]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2015

billboard100_df = billboard100_df.append(temp_df)

In [20]:
# 2016
url = url_template + str(2016)

temp_df = pd.read_html(url, header=0)[0]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2016

billboard100_df = billboard100_df.append(temp_df)

In [21]:
# 2017
url = url_template + str(2017)

temp_df = pd.read_html(url, header=0)[0]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2017

billboard100_df = billboard100_df.append(temp_df)

In [22]:
# 2018
url = url_template + str(2018)

temp_df = pd.read_html(url, header=0)[0]
temp_df.head()
temp_df.columns.values[2] = "Artist"
temp_df = temp_df.drop(temp_df.columns[0], axis=1)
temp_df.Artist = [artist.split(' featuring')[0] for artist in temp_df.Artist]
temp_df.Title = [title.strip('\"') for title in temp_df.Title]
temp_df['Year'] = 2018

billboard100_df = billboard100_df.append(temp_df)

In [31]:
billboard100_df = billboard100_df.reset_index(drop=True)
billboard100_df['Year'] = pd.to_numeric(billboard100_df['Year'])
billboard100_df['Title'] = billboard100_df['Title'].astype(str)
billboard100_df['Artist'] = billboard100_df['Artist'].astype(str)

In [32]:
billboard100_df

,Title,Artist,Year
0,Breathe,Faith Hill,2000
1,Smooth,Santana,2000
2,Maria Maria,Santana,2000
3,I Wanna Know,Joe,2000
4,Everything You Want,Vertical Horizon,2000
5,Say My Name,Destiny's Child,2000
6,I Knew I Loved You,Savage Garden,2000
7,Amazed,Lonestar,2000
8,Bent,Matchbox Twenty,2000
9,He Wasn't Man Enough,Toni Braxton,2000
10,Higher,Creed,2000
11,Try Again,Aaliyah,2000
12,"Jumpin', Jumpin'",Destiny's Child,2000
13,Thong Song,Sisqó,2000
14,Kryptonite,3 Doors Down,2000
15,There You Go,Pink,2000
16,Music,Madonna,2000
17,Doesn't Really Matter,Janet Jackson,2000
18,What a Girl Wants,Christina Aguilera,2000
19,Back at One,Brian McKnight,2000
20,Bye Bye Bye,'N Sync,2000
21,You Sang to Me,Marc Anthony,2000
22,I Need to Know,Marc Anthony,2000
23,Get It On Tonite,Montell Jordan,2000
24,Incomplete,Sisqó,2000
25,I Try,Macy Gray,2000
26,It's Gonna Be Me,'N Sync,2000
27,That's The Way It Is,Celine Dion,2000
28,Country Grammar (Hot Shit),Nelly,2000
29,Bring It All to Me,Blaque,2000
...,...,...,...
1870,Shape of You,Ed Sheeran,2018
1871,I Get the Bag,Gucci Mane,2018
1872,No Brainer,DJ Khaled,2018
1873,Plain Jane,ASAP Ferg,2018
1874,Sky Walker,Miguel,2018
1875,Marry Me,Thomas Rhett,2018
1876,Eastside,"Benny Blanco, Halsey and Khalid",2018
1877,Call Out My Name,The Weeknd,2018
1878,King's Dead,"Jay Rock, Kendrick Lamar, Future and James Blake",2018
1879,Happier,Marshmello and Bastille,2018
1880,Te Boté,"Nio García, Darell and Casper Mágico",2018
1881,Simple,Florida Georgia Line,2018
1882,Lemon,N.E.R.D and Rihanna,2018
1883,1-800-273-8255,Logic,2018
1884,Say Something,Justin Timberlake,2018
1885,I'm Upset,Drake,2018
1886,Get Along,Kenny Chesney,2018
1887,Moonlight,XXXTentacion,2018
1888,What Lovers Do,Maroon 5,2018
1889,X,Nicky Jam and J Balvin,2018
1890,Outside Today,YoungBoy Never Broke Again,2018
1891,Trip,Ella Mai,2018
1892,Dura,Daddy Yankee,2018
1893,Changes,XXXTentacion,2018
1894,Mercy,Brett Young,2018
1895,One Number Away,Luke Combs,2018
1896,Powerglide,Rae Sremmurd,2018
1897,IDGAF,Dua Lipa,2018
1898,Mi Gente,J Balvin and Willy William,2018
1899,Believer,Imagine Dragons,2018

In [53]:
billboard100_df.to_csv('billboard.csv')